/*
 * SubC Compiler - IBM System/370 Code Generator
 *
 * This file implements the code generator for the IBM System/370 architecture.
 * It generates HLASM (High Level Assembler) syntax assembly code.
 *
 * Architecture characteristics:
 *   - 24-bit addressing (16MB address space)
 *   - 32-bit general purpose registers (0-15)
 *   - Big-endian byte order
 *   - Stack grows upward (toward higher addresses)
 *   - IBM Hexadecimal floating point format
 *
 * Register usage:
 *   0  - Work register (not preserved across calls)
 *   1  - Parameter list pointer
 *   2  - Primary accumulator (return value)
 *   3  - Secondary accumulator
 *   4-11 - General purpose (callee-saved)
 *   12 - Base register (program addressability)
 *   13 - Save area pointer (frame pointer equivalent)
 *   14 - Return address
 *   15 - Entry point address / return code
 *
 * S/370 Save Area Layout (18 fullwords, 72 bytes):
 *   +0   Reserved
 *   +4   Pointer to previous save area (backward chain)
 *   +8   Pointer to next save area (forward chain)
 *   +12  14 (return address)
 *   +16  15 (entry point)
 *   +20  0
 *   +24  1
 *   ...
 *   +68  12
 *
 * Copyright (c) 2025 - Public Domain (CC0)
 */

#include <string.h>
#include "defs.h"
#include "data.h"
#include "decl.h"
#include "cgtarget.h"
#include "cg_s370_funcs.h"

/*
 * ============================================================================
 * SECTION: Section Control
 * ============================================================================
 */

void cgs370_data(void) {
    gen("*");
    gen("* Data Section");
    gen("*");
}

void cgs370_text(void) {
    gen("*");
    gen("* Code Section");
    gen("*");
}

static int Func_idx = 0;    /* Function index for MVS labels */
static char Func_name[64];  /* Current function name */
static int Is_main = 0;     /* Flag for main function */

void cgs370_prelude(void) {
    Func_idx = 0;
    Is_main = 0;
    if (TARGET_OS == OS_MVS) {
        genraw("         COPY  PDPTOP\n");
        genraw("         CSECT\n");
        gen("* Program text area");
        gen("         DS    0F");
    } else {
        gen("*");
        gen("* SubC Generated Code for IBM System/370");
        gen("*");
        gen("         PRINT NOGEN");
    }
}

void cgs370_postlude(void) {
    if (TARGET_OS == OS_MVS) {
        genraw("         END   @@MAIN\n");
    } else {
        gen("         END");
    }
}

void cgs370_public(char *s) {
    /* Save function name for use in entry/exit */
    strncpy(Func_name, s, sizeof(Func_name) - 1);
    Func_name[sizeof(Func_name) - 1] = '\0';
    
    /* Check if this is main */
    if (strcmp(s, "Cmain") == 0 || strcmp(s, "main") == 0) {
        Is_main = 1;
        if (TARGET_OS == OS_MVS) {
            gen("         DS    0F");
            gen("         COPY  PDPMAIN");
        }
    } else {
        Is_main = 0;
    }
    
    /* For non-MVS, generate ENTRY directive */
    if (TARGET_OS != OS_MVS) {
        sgen("%s ENTRY %s", "", s);
    }
}

void cgs370_name(char *s) {
    /* Generate data label */
    if (TARGET_OS == OS_MVS) {
        char buf[64];
        sprintf(buf, "%-8s EQU   *", s);
        gen(buf);
    } else {
        sgen("%s:", s, "");
    }
}

void cgs370_funcname(char *s) {
    /* For MVS, function label is generated by entry with PDPPRLG */
    if (TARGET_OS == OS_MVS) {
        return;
    }
    sgen("%s:", s, "");
}

void cgs370_align(void) {
    gen("         DS    0F");
}

/*
 * ============================================================================
 * SECTION: Literal and Clear
 * ============================================================================
 */

void cgs370_lit(int n) {
    ngen("%s L     2,=F'%d'", "        ", n);
}

void cgs370_clear(void) {
    gen("         SR    2,2");
}

void cgs370_clear2(void) {
    gen("         SR    3,3");
}

/*
 * ============================================================================
 * SECTION: Load Operations
 * ============================================================================
 */

void cgs370_ldgb(char *s) {
    gen("         SR    2,2");
    sgen("%s IC    2,%s", "        ", s);
}

void cgs370_ldgw(char *s) {
    sgen("%s L     2,%s", "        ", s);
}

void cgs370_ldlb(int n) {
    gen("         SR    2,2");
    if (TARGET_OS == OS_MVS && n >= 0 && n < 72) {
        /* MVS: parameters accessed via R11 */
        ngen("%s IC    2,%d(11)", "        ", n);
    } else {
        ngen("%s IC    2,%d(,13)", "        ", n);
    }
}

void cgs370_ldlw(int n) {
    if (TARGET_OS == OS_MVS && n >= 0 && n < 72) {
        /* MVS: parameters accessed via R11 */
        ngen("%s L     2,%d(11)", "        ", n);
    } else {
        ngen("%s L     2,%d(,13)", "        ", n);
    }
}

void cgs370_ldsb(int n) {
    gen("         SR    2,2");
    lgen("%s IC    2,%c%d", "        ", n);
}

void cgs370_ldsw(int n) {
    lgen("%s L     2,%c%d", "        ", n);
}

void cgs370_ldla(int n) {
    if (TARGET_OS == OS_MVS && n >= 0 && n < 72) {
        /* MVS: parameters accessed via R11 */
        ngen("%s LA    2,%d(11)", "        ", n);
    } else {
        ngen("%s LA    2,%d(,13)", "        ", n);
    }
}

void cgs370_ldsa(int n) {
    lgen("%s LA    2,%c%d", "        ", n);
}

void cgs370_ldga(char *s) {
    sgen("%s LA    2,%s", "        ", s);
}

void cgs370_indb(void) {
    gen("         SR    0,0");
    gen("         IC    0,0(,2)");
    gen("         LR    2,0");
}

void cgs370_indw(void) {
    gen("         L     2,0(,2)");
}

void cgs370_ldlab(int id) {
    lgen("%s LA    2,%c%d", "        ", id);
}

/*
 * ============================================================================
 * SECTION: Stack Operations
 * ============================================================================
 *
 * Note: S/370 stack grows upward. We use a software stack pointed by 11.
 */

static int Stk = 0;  /* Stack pointer offset */

void cgs370_push(void) {
    if (TARGET_OS == OS_MVS) {
        /* MVS: use R13 for parameter area */
        ngen("%s ST    2,%d(,13)", "        ", Stk);
    } else {
        ngen("%s ST    2,%d(,11)", "        ", Stk);
    }
    Stk += 4;
}

void cgs370_pushlit(int n) {
    ngen("%s L     0,=F'%d'", "        ", n);
    if (TARGET_OS == OS_MVS) {
        /* MVS: use R13 for parameter area */
        ngen("%s ST    0,%d(,13)", "        ", Stk);
    } else {
        ngen("%s ST    0,%d(,11)", "        ", Stk);
    }
    Stk += 4;
}

void cgs370_pop2(void) {
    Stk -= 4;
    if (TARGET_OS == OS_MVS) {
        ngen("%s L     3,%d(,13)", "        ", Stk);
    } else {
        ngen("%s L     3,%d(,11)", "        ", Stk);
    }
}

void cgs370_swap(void) {
    gen("         LR    0,2");
    gen("         LR    2,3");
    gen("         LR    3,0");
}

void cgs370_popptr(void) {
    Stk -= 4;
    if (TARGET_OS == OS_MVS) {
        ngen("%s L     3,%d(,13)", "        ", Stk);
        return;
    }
    ngen("%s L     0,%d(,11)", "        ", Stk);
}

/*
 * ============================================================================
 * SECTION: Arithmetic Operations
 * ============================================================================
 */

void cgs370_add(void) {
    gen("         AR    2,3");
}

void cgs370_sub(void) {
    gen("         SR    3,2");
    gen("         LR    2,3");
}

void cgs370_mul(void) {
    gen("         MR    2,3");
    gen("         LR    2,3");
}

void cgs370_div(void) {
    gen("         LR    0,3");
    gen("         SRDA  0,32");
    gen("         DR    0,2");
    gen("         LR    2,1");
}

void cgs370_mod(void) {
    gen("         LR    0,3");
    gen("         SRDA  0,32");
    gen("         DR    0,2");
    gen("         LR    2,0");
}

void cgs370_neg(void) {
    gen("         LCR   2,2");
}

/*
 * ============================================================================
 * SECTION: Bitwise Operations
 * ============================================================================
 */

void cgs370_and(void) {
    gen("         NR    2,3");
}

void cgs370_ior(void) {
    gen("         OR    2,3");
}

void cgs370_xor(void) {
    gen("         XR    2,3");
}

void cgs370_not(void) {
    gen("         X     2,=F'-1'");
}

void cgs370_shl(void) {
    gen("         SLL   3,0(2)");
    gen("         LR    2,3");
}

void cgs370_shr(void) {
    gen("         SRL   3,0(2)");
    gen("         LR    2,3");
}

/*
 * ============================================================================
 * SECTION: Comparison Operations
 * ============================================================================
 */

static void cgs370_cmp(char *branch_inst) {
    int l1, l2;
    char buf[64];
    
    gen("         CR    3,2");
    l1 = label();
    l2 = label();
    sprintf(buf, "         %s   %c%d", branch_inst, LPREFIX, l1);
    gen(buf);
    gen("         SR    2,2");
    lgen("%s B     %c%d", "        ", l2);
    genlab(l1);
    gen("         LA    2,1");
    genlab(l2);
}

void cgs370_eq(void)  { cgs370_cmp("BE"); }
void cgs370_ne(void)  { cgs370_cmp("BNE"); }
void cgs370_lt(void)  { cgs370_cmp("BL"); }
void cgs370_gt(void)  { cgs370_cmp("BH"); }
void cgs370_le(void)  { cgs370_cmp("BNH"); }
void cgs370_ge(void)  { cgs370_cmp("BNL"); }
void cgs370_ult(void) { cgs370_cmp("BL"); }
void cgs370_ugt(void) { cgs370_cmp("BH"); }
void cgs370_ule(void) { cgs370_cmp("BNH"); }
void cgs370_uge(void) { cgs370_cmp("BNL"); }

/*
 * ============================================================================
 * SECTION: Conditional Branch Operations
 * ============================================================================
 */

static void cgs370_brcond(char *branch_inst, int n, int is_unsigned) {
    int lab;
    
    lab = label();
    
    /* Load second operand from stack if needed */
    if (empty == Q_type) {
        cgs370_pop2();
    } else {
        cgs370_load2();
    }
    
    /* Compare registers */
    if (is_unsigned) {
        gen("         CLR   2,3");
    } else {
        gen("         CR    2,3");
    }
    
    /* Jump over the branch if condition is FALSE */
    char buf[64];
    sprintf(buf, "         %s   %c%d", branch_inst, LPREFIX, lab);
    gen(buf);
    
    /* Take the branch */
    lgen("%s B     %c%d", "        ", n);
    
    genlab(lab);
}

void cgs370_breq(int n)  { cgs370_brcond("BE", n, 0); }
void cgs370_brne(int n)  { cgs370_brcond("BNE", n, 0); }
void cgs370_brlt(int n)  { cgs370_brcond("BL", n, 0); }
void cgs370_brgt(int n)  { cgs370_brcond("BH", n, 0); }
void cgs370_brle(int n)  { cgs370_brcond("BNH", n, 0); }
void cgs370_brge(int n)  { cgs370_brcond("BNL", n, 0); }
void cgs370_brult(int n) { cgs370_brcond("BL", n, 1); }
void cgs370_brugt(int n) { cgs370_brcond("BH", n, 1); }
void cgs370_brule(int n) { cgs370_brcond("BNH", n, 1); }
void cgs370_bruge(int n) { cgs370_brcond("BNL", n, 1); }

/*
 * ============================================================================
 * SECTION: Boolean and Logic Operations
 * ============================================================================
 */

void cgs370_lognot(void) {
    int l1, l2;
    
    gen("         LTR   2,2");
    l1 = label();
    l2 = label();
    lgen("%s BZ    %c%d", "        ", l1);
    gen("         SR    2,2");
    lgen("%s B     %c%d", "        ", l2);
    genlab(l1);
    gen("         LA    2,1");
    genlab(l2);
}

void cgs370_bool(void) {
    int l1, l2;
    
    gen("         LTR   2,2");
    l1 = label();
    l2 = label();
    lgen("%s BNZ   %c%d", "        ", l1);
    gen("         SR    2,2");
    lgen("%s B     %c%d", "        ", l2);
    genlab(l1);
    gen("         LA    2,1");
    genlab(l2);
}

/*
 * ============================================================================
 * SECTION: Pointer Scaling Operations
 * ============================================================================
 */

void cgs370_scale(void) {
    gen("         SLA   2,2");
}

void cgs370_scale2(void) {
    gen("         SLA   3,2");
}

void cgs370_unscale(void) {
    gen("         SRA   2,2");
}

void cgs370_scaleby(int v) {
    if (v == 1) return;
    ngen("%s MH    2,=H'%d'", "        ", v);
}

void cgs370_scale2by(int v) {
    if (v == 1) return;
    ngen("%s MH    3,=H'%d'", "        ", v);
}

void cgs370_unscaleby(int v) {
    if (v == 1) return;
    gen("         SRDA  2,32");
    ngen("%s D     2,=F'%d'", "        ", v);
    gen("         LR    2,3");
}

/*
 * ============================================================================
 * SECTION: Increment/Decrement Operations
 * ============================================================================
 */

void cgs370_ldinc(void) {
    /* Load value for increment via pointer */
}

void cgs370_inc1pi(int v) {
    gen("         L     0,0(,2)");
    ngen("%s A     0,=F'%d'", "        ", v);
    gen("         ST    0,0(,2)");
}

void cgs370_dec1pi(int v) {
    gen("         L     0,0(,2)");
    ngen("%s S     0,=F'%d'", "        ", v);
    gen("         ST    0,0(,2)");
}

void cgs370_inc2pi(int v) { cgs370_inc1pi(v); }
void cgs370_dec2pi(int v) { cgs370_dec1pi(v); }

void cgs370_incpl(int a, int v) {
    ngen("%s L     0,%d(,13)", "        ", a);
    ngen("%s A     0,=F'%d'", "        ", v);
    ngen("%s ST    0,%d(,13)", "        ", a);
}

void cgs370_decpl(int a, int v) {
    ngen("%s L     0,%d(,13)", "        ", a);
    ngen("%s S     0,=F'%d'", "        ", v);
    ngen("%s ST    0,%d(,13)", "        ", a);
}

void cgs370_inclw(int a) { cgs370_incpl(a, 1); }
void cgs370_declw(int a) { cgs370_decpl(a, 1); }
void cgs370_inclb(int a) { cgs370_incpl(a, 1); }
void cgs370_declb(int a) { cgs370_decpl(a, 1); }

void cgs370_incps(int a, int v) {
    lgen("%s L     0,%c%d", "        ", a);
    ngen("%s A     0,=F'%d'", "        ", v);
    lgen("%s ST    0,%c%d", "        ", a);
}

void cgs370_decps(int a, int v) {
    lgen("%s L     0,%c%d", "        ", a);
    ngen("%s S     0,=F'%d'", "        ", v);
    lgen("%s ST    0,%c%d", "        ", a);
}

void cgs370_incsw(int a) { cgs370_incps(a, 1); }
void cgs370_decsw(int a) { cgs370_decps(a, 1); }
void cgs370_incsb(int a) { cgs370_incps(a, 1); }
void cgs370_decsb(int a) { cgs370_decps(a, 1); }

void cgs370_incpg(char *s, int v) {
    sgen("%s L     0,%s", "        ", s);
    ngen("%s A     0,=F'%d'", "        ", v);
    sgen("%s ST    0,%s", "        ", s);
}

void cgs370_decpg(char *s, int v) {
    sgen("%s L     0,%s", "        ", s);
    ngen("%s S     0,=F'%d'", "        ", v);
    sgen("%s ST    0,%s", "        ", s);
}

void cgs370_incgw(char *s) { cgs370_incpg(s, 1); }
void cgs370_decgw(char *s) { cgs370_decpg(s, 1); }
void cgs370_incgb(char *s) { cgs370_incpg(s, 1); }
void cgs370_decgb(char *s) { cgs370_decpg(s, 1); }

void cgs370_inc1iw(void) {
    gen("         L     0,0(,2)");
    gen("         A     0,=F'1'");
    gen("         ST    0,0(,2)");
}

void cgs370_dec1iw(void) {
    gen("         L     0,0(,2)");
    gen("         S     0,=F'1'");
    gen("         ST    0,0(,2)");
}

void cgs370_inc2iw(void) { cgs370_inc1iw(); }
void cgs370_dec2iw(void) { cgs370_dec1iw(); }
void cgs370_inc1ib(void) { cgs370_inc1iw(); }
void cgs370_dec1ib(void) { cgs370_dec1iw(); }
void cgs370_inc2ib(void) { cgs370_inc1iw(); }
void cgs370_dec2ib(void) { cgs370_dec1iw(); }

/*
 * ============================================================================
 * SECTION: Unconditional Branch
 * ============================================================================
 */

void cgs370_brtrue(int n) {
    gen("         LTR   2,2");
    lgen("%s BNZ   %c%d", "        ", n);
}

void cgs370_brfalse(int n) {
    gen("         LTR   2,2");
    lgen("%s BZ    %c%d", "        ", n);
}

void cgs370_jump(int n) {
    lgen("%s B     %c%d", "        ", n);
}

/*
 * ============================================================================
 * SECTION: Switch Statement Support
 * ============================================================================
 */

void cgs370_ldswtch(int n) {
    lgen("%s LA    1,%c%d", "        ", n);
}

void cgs370_calswtch(void) {
    gen("         BALR  14,1");
}

void cgs370_case(int v, int l) {
    ngen("%s DC    F'%d'", "        ", v);
    lgen("%s DC    A(%c%d)", "        ", l);
}

/*
 * ============================================================================
 * SECTION: Store Operations
 * ============================================================================
 */

void cgs370_storib(void) {
    cgs370_pop2();
    gen("         STC   2,0(,3)");
}

void cgs370_storiw(void) {
    cgs370_pop2();
    gen("         ST    2,0(,3)");
}

void cgs370_storlb(int n) {
    ngen("%s STC   2,%d(,13)", "        ", n);
}

void cgs370_storlw(int n) {
    ngen("%s ST    2,%d(,13)", "        ", n);
}

void cgs370_storsb(int n) {
    lgen("%s STC   2,%c%d", "        ", n);
}

void cgs370_storsw(int n) {
    lgen("%s ST    2,%c%d", "        ", n);
}

void cgs370_storgb(char *s) {
    sgen("%s STC   2,%s", "        ", s);
}

void cgs370_storgw(char *s) {
    sgen("%s ST    2,%s", "        ", s);
}

/*
 * ============================================================================
 * SECTION: Function Call Operations
 * ============================================================================
 */

void cgs370_initlw(int v, int a) {
    char buf[64];
    if (TARGET_OS == OS_MVS) {
        /* MVS: use MVC to move literal directly to memory */
        sprintf(buf, "         MVC   %d(4,13),=F'%d'", a, v);
        gen(buf);
    } else {
        ngen("%s L     0,=F'%d'", "        ", v);
        ngen("%s ST    0,%d(,13)", "        ", a);
    }
}

void cgs370_call(char *s) {
    if (TARGET_OS == OS_MVS) {
        /* MVS: LA 1,param_area + L 15,=A(func) + BALR + LR 2,15 */
        ngen("%s LA    1,%d(,13)", "        ", Stk);
        sgen("%s L     15,=A(%s)", "        ", s);
        gen("         BALR  14,15");
        gen("         LR    2,15");
    } else {
        sgen("%s L     15,=V(%s)", "        ", s);
        gen("         BALR  14,15");
    }
}

void cgs370_calr(void) {
    gen("         LR    15,2");
    gen("         BALR  14,15");
}

void cgs370_stack(int n) {
    if (TARGET_OS == OS_MVS) {
        /* MVS: n is the size of local variables, add to Stk */
        ngen("%s A     11,=F'%d'", "        ", n);
        Stk += n;
    } else {
        ngen("%s A     11,=F'%d'", "        ", n);
        Stk -= n;
    }
}

void cgs370_entry(int lsize, int nparams) {
    char buf[128];
    int frame;
    (void)nparams;  /* Not used for S/370 */
    
    if (TARGET_OS == OS_MVS) {
        /* MVS frame calculation:
         * 72 bytes: save area (R14-R12)
         * 16 bytes: reserved area
         * lsize bytes: local variables
         * Round up to multiple of 8 for alignment
         */
        frame = 88 + lsize;
        frame = (frame + 7) & ~7;  /* Align to 8 bytes */
        
        /* MVS-style prologue similar to GCCMVS using PDPPRLG macro */
        sprintf(buf, "* X-func %s prologue", Func_name);
        gen(buf);
        sprintf(buf, "%-8s PDPPRLG CINDEX=%d,FRAME=%d,BASER=12,ENTRY=YES",
                Func_name, Func_idx, frame);
        gen(buf);
        sprintf(buf, "         B     @@FEN%d", Func_idx);
        gen(buf);
        gen("         LTORG");
        sprintf(buf, "@@FEN%d   EQU   *", Func_idx);
        gen(buf);
        gen("         DROP  12");
        gen("         BALR  12,0");
        gen("         USING *,12");
        sprintf(buf, "@@PG%d    EQU   *", Func_idx);
        gen(buf);
        gen("         LR    11,1");      /* 11 = parameter list pointer */
        sprintf(buf, "         L     10,=A(@@PGT%d)", Func_idx);
        gen(buf);
        sprintf(buf, "* Function %s code", Func_name);
        gen(buf);
    } else {
        /* Generic S/370 prologue */
        gen("         STM   14,12,12(13)");
        gen("         LR    12,15");
        gen("         USING *,12");
        gen("         LA    11,72(,13)");
        gen("         ST    13,4(,11)");
        gen("         ST    11,8(,13)");
        gen("         LR    13,11");
    }
    if (TARGET_OS == OS_MVS) {
        Stk = 88;  /* MVS: Start after save area (72) + reserved (16) */
    } else {
        Stk = 72;  /* Start after save area */
    }
}

void cgs370_exit(void) {
    char buf[128];
    
    if (TARGET_OS == OS_MVS) {
        /* MVS-style epilogue - return value in 15 */
        gen("         LR    15,2");      /* Move return value to 15 */
        sprintf(buf, "* Function %s epilogue", Func_name);
        gen(buf);
        gen("         PDPEPIL");
        /* Generate literal pool */
        sprintf(buf, "* Function %s literal pool", Func_name);
        gen(buf);
        gen("         DS    0F");
        gen("         LTORG");
        /* Generate page table */
        sprintf(buf, "* Function %s page table", Func_name);
        gen(buf);
        gen("         DS    0F");
        sprintf(buf, "@@PGT%d   EQU   *", Func_idx);
        gen(buf);
        sprintf(buf, "         DC    A(@@PG%d)", Func_idx);
        gen(buf);
        Func_idx++;
    } else {
        /* Generic S/370 epilogue */
        gen("         L     13,4(,13)");
        gen("         LM    14,12,12(13)");
        gen("         BR    14");
    }
}

/*
 * ============================================================================
 * SECTION: Data Definition
 * ============================================================================
 */

void cgs370_defb(int v) {
    ngen("%s DC    X'%02X'", "        ", v & 0xFF);
}

void cgs370_defw(int v) {
    ngen("%s DC    H'%d'", "        ", v);
}

void cgs370_defp(int v) {
    ngen("%s DC    A(%d)", "        ", v);
}

void cgs370_defl(int v) {
    lgen("%s DC    A(%c%d)", "        ", v);
}

void cgs370_defc(int c) {
    ngen("%s DC    C'%c'", "        ", c);
}

void cgs370_gbss(char *s, int z) {
    char buf[64];
    sprintf(buf, "%dC", z);
    sgen("%-8s DS    %s", s, buf);
}

void cgs370_lbss(char *s, int z) {
    char buf[64];
    sprintf(buf, "%dC", z);
    sgen("%-8s DS    %s", s, buf);
}

/*
 * ============================================================================
 * SECTION: Synthesizer Support
 * ============================================================================
 */

int cgs370_load2(void) {
    cgs370_pop2();
    return 1;
}
