/*
 *	NMH's Simple C Compiler, 2011--2025
 *	Token definitions
 *
 *	Extended to support all C89 type keywords
 */

#ifndef TOKENS_H
#define TOKENS_H

/* tokens */
enum {
	/* Operators - binary */
	SLASH, STAR, MOD, PLUS, MINUS, LSHIFT, RSHIFT,
	GREATER, GTEQ, LESS, LTEQ, EQUAL, NOTEQ, AMPER,
	CARET, PIPE, LOGAND, LOGOR,

	/* Operators - assignment and misc */
	ARROW, ASAND, ASXOR, ASLSHIFT, ASMINUS, ASMOD, ASOR, ASPLUS,
	ASRSHIFT, ASDIV, ASMUL, ASSIGN, AUTO, BREAK, CASE, CHAR, COLON,
	COMMA, CONST, CONTINUE, DECR, DEFAULT, DO, DOT, DOUBLE, ELLIPSIS,
	ELSE, ENUM, EXTERN, FLOAT, FOR, IDENT, IF, INCR, INT, INTLIT,
	LBRACE, LBRACK, LONG, LPAREN, NOT, QMARK, RBRACE, RBRACK,
	REGISTER, RETURN, RPAREN, SEMI, SHORT, SIGNED, SIZEOF, STATIC,
	STRLIT, STRUCT, SWITCH, TILDE, TYPEDEF, UNION, UNSIGNED, VOID,
	VOLATILE, WHILE, XEOF, XMARK,

	/* Literals for new types */
	FLOATLIT,           /* floating-point literal */

	/* Preprocessor directives */
	P_DEFINE, P_ELSE, P_ELSENOT, P_ENDIF, P_ERROR, P_IFDEF,
	P_IFNDEF, P_INCLUDE, P_LINE, P_PRAGMA, P_UNDEF
};

#endif /* TOKENS_H */
